# Generated by Django 4.1.7 on 2023-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_chamada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chamada",
            name="description",
        ),
        migrations.RemoveField(
            model_name="chamada",
            name="done",
        ),
        migrations.AddField(
            model_name="chamada",
            name="numero",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="chamada",
            name="receptor",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
